on:
    workflow_call:

jobs:
    unittest:
        runs-on: ubuntu-22.04
        permissions:
            contents: read
            pull-requests: write
            issues: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Python
              uses: ./.github/actions/setup-python
              with:
                  python-version: '3.12'
                  environment: 'dev'

            - name: Test with pytest and coverage
              run: |
                  coverage run -m pytest
                  coverage report -m --omit="test_*" > coverage.txt
                  coverage html --omit="test_*"

            - name: Capture coverage report
              id: get_coverage
              run: |
                  echo "coverage<<EOF" >> $GITHUB_OUTPUT
                  cat coverage.txt >> $GITHUB_OUTPUT
                  echo "EOF" >> $GITHUB_OUTPUT

            - name: Add coverage report to summary
              run: |
                  echo "## Coverage Report" >> $GITHUB_STEP_SUMMARY
                  echo '```' >> $GITHUB_STEP_SUMMARY
                  cat coverage.txt >> $GITHUB_STEP_SUMMARY
                  echo '```' >> $GITHUB_STEP_SUMMARY

            - name: Create or update PR comment with coverage report
              if: ${{ github.event_name == 'pull_request' }}
              uses: peter-evans/create-or-update-comment@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  issue-number: ${{ github.event.pull_request.number }}
                  body: |
                      ## Coverage Report
                      ```
                      ${{ steps.get_coverage.outputs.coverage }}
                      ```

            - name: Fail if coverage is below threshold
              run: |
                  coverage_result=$(tail -n 1 coverage.txt | awk '{print $NF}' | sed 's/%//')
                  echo "Coverage: $coverage_result%"
                  if (( $(echo "$coverage_result < 70" | bc -l) )); then
                    echo "Coverage is below 70%. Failing the pipeline."
                    exit 1
                  fi
